databases:
  - name: moneymate
    databaseName: moneymate
    user: moneymate

services:
  - type: web
    name: moneymate
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moneymate
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
